apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80          # Service port (inside cluster)
    targetPort: 80     # Pod port
    nodePort: 30080    # External port (accessible from worker/master IP)
