apiVersion: v1
kind: Namespace
metadata:
  name: lab-test
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: lab-test
type: Opaque
stringData:
  mongo-root-username: mongoadmin
  mongo-root-password: mongopass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: lab-test
data:
  database-url: mongo-service
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: lab-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: lab-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: lab-test
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      initContainers:
        - name: cleanup
          image: busybox
          command: ['sh', '-c', 'rm -rf /data/db/* /data/db/..?* /data/db/.[!.]* 2>/dev/null || true']
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: lab-test
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
